import type { Metadata } from "next";
import { siteConfig } from "@/config/site";
import { PageContainer } from "@/components/shared/page-container";
import { Breadcrumbs } from "@/components/shared/breadcrumbs";

export const metadata: Metadata = {
  title: "Privacy Policy",
  description: `GETX Privacy Policy — what data we collect, how we use it, your rights and how to contact us.`,
};

const LAST_UPDATED = "June 2026";

export default function PrivacyPage() {
  return (
    <main className="flex-1 py-8 min-[761px]:py-12">
      <PageContainer className="max-w-3xl">
        <Breadcrumbs
          items={[{ label: "Home", href: "/" }, { label: "Privacy Policy" }]}
        />

        <header className="mt-6 mb-8">
          <h1 className="font-heading text-[clamp(26px,4vw,36px)] font-extrabold">
            Privacy Policy
          </h1>
          <p className="mt-2 text-sm text-faint">Last updated: {LAST_UPDATED}</p>
        </header>

        <div className="flex flex-col gap-8 font-sans text-[15px] leading-relaxed text-muted-foreground">
          <section>
            <h2 className="mb-2 font-heading text-lg font-bold text-foreground">What We Collect</h2>
            <p>
              We collect information you provide when registering (name, email address, password
              hash) and information generated by your activity on the platform (listings, orders,
              messages). For payment verification we collect the metadata required by our payment
              processors — we never store full card numbers, CVVs, or raw crypto wallet keys.
            </p>
          </section>

          <section className="border-t border-border pt-6">
            <h2 className="mb-2 font-heading text-lg font-bold text-foreground">How We Use It</h2>
            <p>
              Your data is used to operate the marketplace (process orders, manage escrow, deliver
              items), prevent fraud, send transactional notifications (order updates, dispute
              outcomes), and improve the platform. We do not sell your personal data to third
              parties or use it for targeted advertising.
            </p>
          </section>

          <section className="border-t border-border pt-6">
            <h2 className="mb-2 font-heading text-lg font-bold text-foreground">Cookies</h2>
            <p>
              We use strictly necessary session cookies to keep you logged in and to protect
              against CSRF attacks. We do not use third-party advertising cookies. Analytics are
              server-side only and do not require a cookie consent banner.
            </p>
          </section>

          <section className="border-t border-border pt-6">
            <h2 className="mb-2 font-heading text-lg font-bold text-foreground">Third-Party Processors</h2>
            <p>
              We share the minimum data required with these processors to operate the platform:
              Razorpay and CoinGate (payment processing), Cloudflare (DDoS protection, Turnstile
              bot detection), Neon and Vercel (database and hosting infrastructure). Each processor
              has their own privacy policy and is contractually bound to handle your data securely.
            </p>
          </section>

          <section className="border-t border-border pt-6">
            <h2 className="mb-2 font-heading text-lg font-bold text-foreground">Your Rights</h2>
            <p>
              Under the Indian IT Act 2000 and PDPB framework you have the right to access the
              personal data we hold about you, correct inaccuracies, and request deletion of your
              account and associated data. To exercise these rights, email{" "}
              <a href="mailto:support@getx.live" className="text-primary hover:underline">
                support@getx.live
              </a>
              . We will respond within 30 days.
            </p>
          </section>

          <section className="border-t border-border pt-6">
            <h2 className="mb-2 font-heading text-lg font-bold text-foreground">Data Retention</h2>
            <p>
              We retain your account data for as long as your account is active. Transaction
              records (orders, ledger entries) are retained for 7 years to comply with financial
              regulations. KYC documents are stored in an encrypted private bucket and accessed
              only when required for dispute resolution or regulatory compliance.
            </p>
          </section>

          <section className="border-t border-border pt-6">
            <h2 className="mb-2 font-heading text-lg font-bold text-foreground">Contact</h2>
            <p>
              Privacy questions? Contact our data team at{" "}
              <a href="mailto:support@getx.live" className="text-primary hover:underline">
                support@getx.live
              </a>{" "}
              with the subject line &quot;Privacy Request&quot;.{" "}
              {siteConfig.name} · {siteConfig.domain}
            </p>
          </section>
        </div>
      </PageContainer>
    </main>
  );
}
